import { marked } from 'marked';
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import { fetchEntry } from '../../lib/contentful';

const rendererMD = new marked.Renderer();
const markedOpts = {
  renderer: rendererMD,
};

const Home: NextPage = ({ content }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div dangerouslySetInnerHTML={{
          __html: content
        }} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getServerSideProps(ctx) {
  const { params } = ctx;
  const { slug } = params;

  // 获取文章内容
  const entrys = await fetchEntry(slug);
  console.log(entrys.items[0], 'entrys');

  const fieldContent = entrys?.items[0]?.fields?.content
  
  const content = marked(fieldContent, markedOpts)

  return {
    props: {
      content
    },
  }
}

export default Home
