import { NextPage, GetServerSideProps } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { fetchEntries, IPost } from 'lib/contentful';
import PostCard from 'components/PostCard';
import { Entry } from 'contentful'

interface HomeProps {
  posts: Array<Entry<IPost>>;
}

const Home: NextPage<HomeProps> = ({ posts }) => {
  
  return (
    <div>
      <Head>
        <title>Lengband Blog</title>
        <meta name="description" content="lengband blog, generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='text-xl mb-6 font-bold tracking-wide'>最近更新</div>
      <div>
        {
          posts.map((post: Entry<IPost>) => {
            return (
              <PostCard key={post.sys.id} post={post} />
            )
          })
        }
      </div>
    </div>
  )
}

export const getServerSideProps: GetServerSideProps = async (context) => {
  const { items = [] } = await fetchEntries('post', 10);
  
  return {
    props: {
      posts: items,
    }
  }
}

export default Home
